Added translation of the tutorials
translation-gang/docs-ru pull request #123
Opened 2023-01-08 08:59 UTC by Ibochkarev

Added translation of the tutorials

2023-01-08 10:23 UTC, Alex-Sokolov requested changes

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/guide/introduction.md
> +
Вроде как везде в таких блоках не делали отступ пустой строкой, зачем тогда тут и в quick-start было их добавлять. Надо чтобы везде было единообразно

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +Цель этого руководства - быстро дать вам представление о том, каково это - работать с Vue прямо в браузере. Она не стремится быть всеобъемлющей, и вам не нужно понимать все, прежде чем двигаться даль
Цель этого руководства — дать быстрое представление каким образом можно работать с Vue в браузере

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +Цель этого руководства - быстро дать вам представление о том, каково это - работать с Vue прямо в браузере. Она не стремится быть всеобъемлющей, и вам не нужно понимать все, прежде чем двигаться даль
понимать всё

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +Цель этого руководства - быстро дать вам представление о том, каково это - работать с Vue прямо в браузере. Она не стремится быть всеобъемлющей, и вам не нужно понимать все, прежде чем двигаться даль
Но после его завершения рекомендуем прочитать руководство, где рассматривается каждая тема подробно

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +Вы можете редактировать код <span class="wide">справа</span><span class="narrow">внизу</span> и видеть, как результат мгновенно обновляется. На каждом этапе будет представлена основная функция Vue, и
На каждом шаге будет представлена одна из основных возможностей Vue

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +Вы можете редактировать код <span class="wide">справа</span><span class="narrow">внизу</span> и видеть, как результат мгновенно обновляется. На каждом этапе будет представлена основная функция Vue, и
Кнопка тоже переведена будет

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +Если вы опытный разработчик, пришедший из Vue 2 или других фреймворков, вы можете изменить несколько настроек, чтобы наилучшим образом использовать этот учебник. Если вы новичок, рекомендуется исполь
Тоже куча "вы" без которых бы постараться переписать

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +<summary>Детали настройки учебника</summary>
Подробности настройки учебника

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +- Vue предлагает два стиля API: Options API и Composition API. Этот учебник предназначен для работы с обоими - вы можете выбрать предпочитаемый стиль, используя переключатели **API Preference** вверх
Этот учебник разработан для работы с любым —

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +- Vue предлагает два стиля API: Options API и Composition API. Этот учебник предназначен для работы с обоими - вы можете выбрать предпочитаемый стиль, используя переключатели **API Preference** вверх
Справочник API

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-1/description.md
> +- Вы также можете переключаться между SFC-режимом или HTML-режимом. В первом будут показаны примеры кода в формате <a target="_blank" href="/guide/introduction.html#single-file-components">Single-Fil
Однофайловые компоненты

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
>  <div class="composition-api">
Перед примером одну пустую строку думаю можно вернуть

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
> +`reactive()` работает только с объектами (включая массивы и встроенные типы, такие как `Map` и `Set`). С другой стороны, `ref()` может принимать любой тип значения и создавать объект, который раскрыв
который предоставляет доступ к внутреннему значению через свойство

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
>  message.value = 'Changed'
Строки в примере остались на англ

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
> +Подробности о `reactive()` и `ref()` обсуждаются в <a target="_blank" href="/guide/essentials/reactivity-fundamentals.html">Гид - Основы реактивности</a>.
Руководство —

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
> +Реактивное состояние, объявленное в блоке `<script setup>` компонента, может быть использовано непосредственно в шаблоне. Так мы можем вывести динамический текст на основе значения объекта `counter`
можно использовать в шаблоне

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
> +Реактивное состояние, объявленное в блоке `<script setup>` компонента, может быть использовано непосредственно в шаблоне. Так мы можем вывести динамический текст на основе значения объекта `counter`
используя синтаксис двойных фигурных скобок

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
В примере осталась непереведённая строка

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
> +Свойства возвращаемого объекта будут доступны в шаблоне. Вот как мы можем вывести динамический текст на основе значения `message`, используя синтаксис усов:
синтаксис двойных фигурных скобок (mustache) если хочется именно уточнить, а то выше так тут иначе

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
>  ```
Пример без перевода

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
Пример без перевода

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
> +Свойство `message` будет доступно в шаблоне. Вот как мы можем вывести динамический текст, основанный на значении `message`, используя синтаксис усов:
Аналогично, синтаксис усов нигде не упоминается в таком виде

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-2/description.md
> +Содержимое внутри усов не ограничивается только идентификаторами или путями - мы можем использовать любое допустимое выражение JavaScript:
внутри двойных фигурных скобок

2023-01-08 10:23 UTC, Alex-Sokolov commented on src/tutorial/src/step-3/description.md
> +В Vue усы используются только для интерполяции текста. Чтобы привязать атрибут к динамическому значению, мы используем директиву `v-bind`:
синтаксис двойных фигурных скобок / можно подглядывать как уже переводилось в документации 3 версии

2023-01-08 10:40 UTC, Ibochkarev commented on src/guide/introduction.md
> +
Потому, что есть правила работы с Markdown 

И конкретно тут ошибка, что нет пробела перед списком

https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md032

2023-01-09 16:31 UTC, merged

2023-01-09 16:31 UTC, Alex-Sokolov commented
Спасибо :)