Added new translation tutorials
translation-gang/docs-ru pull request #127
Opened 2023-01-10 15:57 UTC by Ibochkarev

Added new translation tutorials

2023-01-11 08:40 UTC, Alex-Sokolov requested changes

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-10/description.md
> +`watch()` может напрямую просматривать ссылку, и коллбэк запускается всякий раз, когда изменяется значение `count`. `watch()` может также следить за другими типами источников данных - более подробно
```suggestion
`watch()` может напрямую отслеживать реактивную ссылку, а коллбэк запускается всякий раз, когда изменяется значение `count`. `watch()` также может следить за другими типами источников данных — более подробно об этом говорится в разделе  <a target="_blank" href="/guide/essentials/watchers.html">Руководство - Наблюдатели</a>.
```

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-10/description.md
> +Более практичным примером, чем ведение журнала в консоли, была бы выборка новых данных при изменении идентификатора. Код, который имеем, извлекает данные todos из макетного API при монтировании компо
```suggestion
Более практичным примером, чем вывод информации в консоли, была бы выборка новых данных при изменении ID. Код, который имеем, извлекает данные todos из мока API при монтировании компонента. Существует также кнопка, которая увеличивает ID задачи, который должен быть извлечен. Попробуйте реализовать наблюдатель, который извлекает новое задание при нажатии кнопки.
```

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-11/description.md
> +Также необходимо зарегистрировать компонент с помощью опции `components`. Здесь используем сокращение свойства объекта, чтобы зарегистрировать компонент `ChildComp` под ключом `ChildComp`.
```suggestion
Также необходимо зарегистрировать компонент с помощью опции `components`. Здесь используем сокращённую запись свойства объекта, чтобы зарегистрировать компонент `ChildComp` под ключом `ChildComp`.
```

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-11/description.md
> +Поскольку записываем шаблон в DOM, он будет подчиняться правилам разбора браузера, которые не чувствительны к регистру имен тегов. Поэтому нужно использовать имя в регистре kebab-cased для ссылки на
```suggestion
Поскольку шаблон указываем в DOM, то он будет подчиняться правилам разбора браузера, которые не чувствительны к регистру имен тегов. Поэтому нужно использовать имя в формате kebab-cased для ссылки на дочерний компонент:
```

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-11/description.md
>  Now try it yourself - import the child component and render it in the template.
Осталось без перевода

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-12/description.md
> +Дочерний компонент может принимать входные данные от родительского через **props**. Во-первых, ему необходимо объявить реквизиты, которые он принимает:
Везде именуем как "входные параметры", а не как "реквизиты"

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-12/description.md
> +Обратите внимание, что `defineProps()` является макросом времени компиляции и не нуждается в импорте. После объявления входного параметра `msg` может быть использован в шаблоне дочернего компонента.
```suggestion
Обратите внимание, что `defineProps()` является макросом времени компиляции и не нуждается в импорте. После объявления входного параметра, `msg` можно использовать в шаблоне дочернего компонента. К нему также можно получить доступ в JavaScript через возвращаемый объект `defineProps()`.
```

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-12/description.md
>  ```
В примере выше остались комментарии без перевода

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-12/description.md
> +После объявления входного параметра `msg` становится доступным для `this` и может быть использован в шаблоне дочернего компонента. Полученные входные параметры передаются в `setup()` в качестве перво
```suggestion
После объявления входного параметра `msg`, он станет доступным через `this` и может использоваться в шаблоне дочернего компонента. Полученные входные параметры передаются в `setup()` в качестве первого аргумента.
```

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-12/description.md
>  }
В примере выше остался комментарий без перевода

2023-01-11 08:40 UTC, Alex-Sokolov commented on src/tutorial/src/step-12/description.md
> +После объявления входного параметра `msg` становится доступным для `this` и может быть использован в шаблоне дочернего компонента.
```suggestion
После объявления входного параметра `msg` становится доступным через `this` и может быть использован в шаблоне дочернего компонента.
```

2023-01-12 17:02 UTC, Alex-Sokolov commented
Несколько комментариев осталось без резолва

2023-08-20 00:40 UTC, Leronez commented
resolves #202 #203 #204

2023-08-30 09:28 UTC, Alex-Sokolov commented
Остались комментарии где без перевода

2024-01-19 03:55 UTC, Ibochkarev commented on src/tutorial/src/step-11/description.md
>  Now try it yourself - import the child component and render it in the template.
```suggestion
Теперь попробуйте самостоятельно - импортируйте дочерний компонент и укажите его в шаблоне.
```

2024-01-19 03:55 UTC, Ibochkarev commented on src/tutorial/src/step-12/description.md
> +Дочерний компонент может принимать входные данные от родительского через **props**. Во-первых, ему необходимо объявить реквизиты, которые он принимает:
```suggestion
Дочерний компонент может принимать входные данные от родительского через **props**. Во-первых, ему необходимо объявить входные параметры, которые он принимает:
```

2024-01-19 03:57 UTC, Ibochkarev commented
@Alex-Sokolov привет!

Нужен апрув с твоей стороны

2024-01-21 09:50 UTC, Alex-Sokolov approved these changes

2024-01-21 10:12 UTC, merged