(fix): локализация страницы "Наблюдатели" /guide/essentials/watchers.html
translation-gang/docs-ru pull request #146
Opened 2023-06-27 11:49 UTC by eugene-kulikov

## Description of Problem
Отсутсвие перевода на странице /guide/essentials/watchers.html

## Proposed Solution
Добавлена локализация для выше указанной страницы

## Additional Information
Есть вопрос по переводу  "Deep Watchers". В предложенном пул реквесте перевел как "Глубокие наблюдатели", но в проекте есть упоминание как "Глубинные наблюдатели". Какая версия считается корректной или можно использовать обе?

2023-06-28 11:39 UTC, Alex-Sokolov requested changes

2023-06-28 11:39 UTC, Alex-Sokolov commented on src/guide/essentials/watchers.md
Выше осталось без перевода

2023-06-28 11:39 UTC, Alex-Sokolov commented on src/guide/essentials/watchers.md
>  </div>
Выше осталось без перевода

2023-06-28 11:39 UTC, Alex-Sokolov commented on src/guide/essentials/watchers.md
Выше осталось без перевода

2023-06-28 11:39 UTC, Alex-Sokolov commented on src/guide/essentials/watchers.md
Выше осталось без перевода

2023-06-28 11:39 UTC, Alex-Sokolov commented on src/guide/essentials/watchers.md
Ниже осталось без перевода

2023-06-28 11:39 UTC, Alex-Sokolov commented
Наверное проще будет "глубокие" просто везде сделать и там тоже поменять. Глубинные не очень много ясности вносят

Часть примеров для composition не были переведы, а надо бы :)

2023-06-28 12:53 UTC, eugene-kulikov commented
Упустил примеры для composition, поправлю

2023-06-29 15:26 UTC, Alex-Sokolov approved these changes

2023-06-29 15:26 UTC, merged

2023-06-29 15:26 UTC, Alex-Sokolov commented
Спасибо!