update .gitignore and composition-api-faq.md
translation-gang/docs-ru pull request #187
Opened 2023-08-08 14:30 UTC by 3lement3

## Description of Problem
Перевод composition-api-faq.md

## Proposed Solution
Переведено composition-api-faq.md и добавлена строка .idea в .gitignore

2023-08-30 10:50 UTC, Alex-Sokolov commented
@3lement3 поправьте чтобы в ПР было только про документацию. Игнорирование каких-то других файлов для всех миллионов IDE делать в рамках проекта неразумно, это должно настраиваться глобально на вашей машине

2023-08-30 11:27 UTC, Alex-Sokolov requested changes

2023-08-30 11:27 UTC, Alex-Sokolov commented on src/guide/extras/composition-api-faq.md
> +Если вы намерены использовать исключительно Composition API (наряду с перечисленными выше параметрами), вы можете сократить свой производственный пакет на несколько килобайт с помощь [compile-time fl
```suggestion
Если вы намерены использовать исключительно Composition API (наряду с перечисленными выше параметрами), вы можете уменьшить сборку для production на несколько килобайт с помощь [compile-time flag](https://github.com/vuejs/core/tree/main/packages/vue#bundler-build-feature-flags) который удаляет код, связанный с API параметров, из Vue. Обратите внимание, что это также влияет на компоненты Vue в ваших зависимостях.
```

2023-08-30 11:27 UTC, Alex-Sokolov commented on src/guide/extras/composition-api-faq.md
> +- Проблема устаревшего закрытия в сочетании с параллельными функциями затрудняет определение того, когда запускается часть кода хуков, и делает работу с изменяемым состоянием, которое должно сохранят
```suggestion
- Проблема устаревшего замыкания в сочетании с параллельными функциями затрудняет определение того, когда запускается часть кода хуков, и делает работу с изменяемым состоянием, которое должно сохраняться при рендеринге (через `useRef`) громоздкой.
```

2023-09-29 20:42 UTC, 3lement3 commented on .gitignore
> +.idea
Вернул как было

2023-09-29 20:44 UTC, 3lement3 commented on src/guide/extras/composition-api-faq.md
>  </template>
Исправил

2023-11-06 20:05 UTC, livsi commented
@Alex-Sokolov Изменений в .gitignore уже нет, что мешает принять PR?

2023-11-06 20:11 UTC, livsi commented on src/guide/extras/composition-api-faq.md
> +Composition API - это набор API, который позволяет нам создавать компоненты Vue, используя импортированные функции вместо объявления опций. Это зонтичный термин, который охватывает следующие API:
вместо "зонтичный термин", который является калькой английского, лучше использовать "обобщающий термин"

2023-11-13 20:02 UTC, 3lement3 commented on src/guide/extras/composition-api-faq.md
> +Composition API - это набор API, который позволяет нам создавать компоненты Vue, используя импортированные функции вместо объявления опций. Это зонтичный термин, который охватывает следующие API:
Исправил

2024-01-19 03:58 UTC, Ibochkarev approved these changes
Спасибо!

2024-01-19 03:58 UTC, Ibochkarev commented
@Alex-Sokolov нужен твой апрув

2024-01-21 13:08 UTC, Alex-Sokolov approved these changes

2024-01-21 13:10 UTC, merged