(fix): Локализация - api/sfc-spec.md
translation-gang/docs-ru pull request #247
Opened 2023-10-03 01:37 UTC by Leronez

## Description of Problem

Отсутствие перевода на странице api/sfc-spec.md 

## Proposed Solution

Добавлена локализация для вышеуказанной страницы

## Additional Information

resolved #246

2024-01-18 09:00 UTC, Ibochkarev requested changes

2024-01-18 09:00 UTC, Ibochkarev commented on src/api/sfc-spec.md
> +Каждый файл `*.vue` состоит из трёх типов языковых секций верхнего уровня: `<template>`, `<script>`, и `<style>`, а также могут быть дополнительные пользовательские секции:
```suggestion
Каждый файл `*.vue` состоит из трёх типов языковых секций верхнего уровня: `<template>`, `<script>`, и `<style>`, а также может содержать дополнительные пользовательские секции:
```

2024-01-18 09:00 UTC, Ibochkarev commented on src/api/sfc-spec.md
> +- Содержимое будет извлечено и передано в `@vue/compiler-dom`, где предварительно скомпилируется в JavaScript render-функцию и и будет присоединено к экспортируемому компоненту в качестве его опции `
```suggestion
- Содержимое будет извлечено и передано в `@vue/compiler-dom`, где предварительно скомпилируется в JavaScript render-функцию и будет присоединено к экспортируемому компоненту в качестве его опции `render`.
```

2024-01-19 02:37 UTC, Leronez commented on src/api/sfc-spec.md
> +Каждый файл `*.vue` состоит из трёх типов языковых секций верхнего уровня: `<template>`, `<script>`, и `<style>`, а также могут быть дополнительные пользовательские секции:
Исправлено

2024-01-19 02:37 UTC, Leronez commented on src/api/sfc-spec.md
> +- Содержимое будет извлечено и передано в `@vue/compiler-dom`, где предварительно скомпилируется в JavaScript render-функцию и и будет присоединено к экспортируемому компоненту в качестве его опции `
Исправлено

2024-01-19 03:52 UTC, Ibochkarev approved these changes

2024-01-19 03:52 UTC, merged