Draft: Перевод Глоссария
translation-gang/docs-ru pull request #301
Opened 2024-01-23 12:22 UTC by Sdju

Перевод будет разбит на 2+ части, так как некоторые переводы важно согласовать с сообществом для получения консистентного перевода.

На данный момент переведено начало и все заголовки.
Хочется обсудить их корректность и в случае одобрения, то данные переводы должны быть выдержаны на протяжении всей работы связанной с переносом на русский язык.

Часть терминов взята из уже использующихся в репозитории. 
Часть из старого глоссария: https://gist.github.com/dsvitnev/92d985fbe1dda36e898618e59813d60eэ
Скорее всего его стоит актуализировать и опубликовать тут в виде вики странички (как напр. в укр. версии https://github.com/vuejs-translations/docs-uk/wiki/Глосарій)

2024-01-23 12:36 UTC, srsad commented on src/glossary/index.md
> +## Планировщий (scheduler) {#scheduler}
Планировщик

2024-01-23 12:43 UTC, Ibochkarev commented on src/glossary/index.md
> +## шаблонный указатель (template ref) {#template-ref}
С большой буквы

2024-01-23 12:59 UTC, Hekikai commented on src/glossary/index.md
> +*Асинхронный компонент (async component)* это обертка вокруг другого компонента, которая обеспечивает обёрнутому компоненту ленивую подгруздку. Это типичный способ уменьшить размер сбилженных `.js` ф
сбилженных `.js` файлов, через - здесь не нужна запятая  
Я бы еще добавил "на небольшие чанки (chunks)", чтобы было понятно, откуда слово

2024-01-23 12:59 UTC, Hekikai commented on src/glossary/index.md
> +Термин *композабл* описывает общий паттерн во Vue. Это не отдельная функция Vue, это просто способ использования фреймворка [Composition API](#composition-api).
это просто способ использования фреймворка - переведено достаточно прямо, хотя смысл на английском немного в другом. Может стоит подумать в сторону - "Это не отдельная функция Vue, это просто способ использовать Composition API, который предоставляет фреймворк"

2024-01-23 12:59 UTC, Hekikai commented on src/glossary/index.md
> +* Композаблы используются для инкапсулции и переиспользования логики с состоянием.
инкапсулции - инкапсуляции.

2024-01-23 12:59 UTC, Hekikai commented on src/glossary/index.md
> +Как и в случае со многими паттернами, могут возникнуть разногласия по поводу того, подходит ли конкретный код под этот ярлык. Не все служебные функции JavaScript являются композаблами. Если функция н
Я бы написал более четче - "код под этот ярлык." - "код под это название (композабл)."  
Если не ожидается что она - Если не ожидается, что она...

2024-01-23 12:59 UTC, Hekikai commented on src/glossary/index.md
> +## Побочное действие (side effect) {#side-effect}
Предлагаю так и оставить - Сайд-эффект  
Я бы сразу не понял про "побочное действие" 😄

2024-01-23 13:02 UTC, Sdju commented on src/glossary/index.md
> +## Побочное действие (side effect) {#side-effect}
Я бы тоже, но в других местах уже именно так употребляется: http://localhost:5173/guide/essentials/computed.html#getters-should-be-side-effect-free
И в других местах тоже встречал

2024-01-23 13:26 UTC, Sdju commented
Сейчас непонятно как все-таки переводить "emit events" - где-то это называют "генерацией событий" (напр, в интерактивном учебнике).
Где-то как "испускание событий" (напр в руководстве).

Нужно выбрать что-то одно. Генерация событий для меня звучит гораздо более естественно

2024-01-23 13:27 UTC, Hekikai commented
Я "За" такое:  
Side effect - сайд эффект
Emit events - генерация событий

2024-01-23 15:03 UTC, srsad commented on src/glossary/index.md
> +## Побочное действие (side effect) {#side-effect}
Тоже хотел по этому поводу написать коммент, так как "побочные действия" у меня не сразу ассоциировались с "сайд эффект". Но так как в скобочках есть пояснения, то забил...
Но если выбирать единый стандарт, то однозначно оставить - сайд эффект

2024-02-01 07:15 UTC, Ibochkarev commented
@Sdju Привет!

Подскажи, пожалуйста, в каком состоянии перевод?

2024-02-01 07:49 UTC, Sdju commented
> @Sdju Привет!
> 
> Подскажи, пожалуйста, в каком состоянии перевод?

Привет в процессе. Должен был из-за командировки приостановиться до этого понедельника

2024-02-12 02:00 UTC, Sdju commented
Перевод завершен. Нужно внимательно его проверить

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Термин *композабл* описывает общий паттерн во Vue. Это не отдельная функция Vue, это просто способ использования подхода [Composition API](#composition-api).
UPD: ты как раз ниже перевел как "один из двух стилей". Я думаю, можно оставить для консистенции слово "стиль"

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +*Пользовательский элемент* - это возможность в стандарте [Веб-компонентов](#web-component), которая реализована в современных веб-браузерах. Это возможность использовать пользовательский HTML-элемент
это возможность в стандарте, которая реализована в современных веб-браузерах.  
Как-то не очень читается. Давай попробуем  
это функциональность стандарта Веб-компонентов, которая реализована в современных веб-браузерах.

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +- [Руководство - Render-функции & JSX - Функциональные компоненты](/guide/extras/render-function.html#functional-components)
Render-функции & JSX - Render-функции и JSX

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +## Подъем (hoisting) {#hoisting}
Предлагаю не переводить, либо переводить как "всплытие"  
Такого варианта почти нигде не встречал

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +В API Options каждый хук предоставляется как отдельная опция, например `mounted`. В Composition API вместо этого используются функции, например `onMounted()`.
В API Options - В Options API

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
>  A component can have multiple slots, differentiated by name. Slots other than the default slot are referred to as *named slots*.
Английский перевод остался

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Компонент может иметь несколько слотов, различающихся по имени. Слоты, отличные от слота по умолчанию, называются *именными слотами*.
называются *именными слотами*. - называются *именованными слотами*.

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
>  ## Options API {#options-api}
Удалить?

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Компоненты Vue определяются с помощью объектов. Свойства этих объектов компонентов называют *опции*.
называют *опции*. - называются *опциями*.  
Первый вариант не так интуитивно читается, прочитал где-то с 3 раза))

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Сама функция `setup()` является опцией компонента, поэтому ее *можно* описать как часть Options API. Однако это не то как термин "Options API" обычно используется. Вместо этого функция `setup()` расс
Однако это не то как термин "Options API" обычно используется.  
Однако это не обычное использование термина "Options API".

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Во всех случаях входные параметры - это свойства, которые передаются из вне.
передаются из вне. - передаются извне.

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +- [Руководство - Render-функции & JSX](/guide/extras/render-function.html)
Render-функции & JSX - Render-функции и JSX

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Пробрасывание(`provide`) и инъекция(`inject`) - это форма взаимодействия между компонентами.
https://github.com/translation-gang/docs-ru/pull/331#issuecomment-1935502617

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Пробрасывание(`provide`) и инъекция(`inject`) - это форма взаимодействия между компонентами.
форма взаимодействия - способ взаимодействия

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
>  `watchEffect()` is the most direct way to create an effect. Various other parts of Vue use effects internally. e.g. component rendering updates, `computed()` and `watch()`.
Английский вариант остался

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +`watchEffect()` - это самый прямой способ создания эффекта. Различные другие части Vue используют эффекты внутри себя. Например, функция обновления рендеринга, `computed()` и `watch()`.
это самый прямой способ создания эффекта. - это самый простой способ создания эффекта.

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Система реактивности может быть реализована различными способами. Например, это можно сделать с помощью статического анализа кода для определения его зависимостей. Однако Vue не использует такую тип
не использует такую тип системы реактивности. - не использует такой тип системы реактивности.

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Вместо этого система реактивности Vue отслеживает доступ к свойствам во время выполнения. Для этого используются как Proxy-обертки, так и функции getter/setter для свойств.
функции getter/setter - такого нет. Есть дескрипторы свойств get/set.  
Предлагаю их оставить, чтобы было понятно, о чем реально идет речь

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +- [Руководство — Render-функции & JSX](/guide/extras/render-function.html)
Render-функции & JSX - Render-функции и JSX

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Планировщик - это часть внутреннего устройства Vue, которая контролирует когда [реактивные эффекты](#reactive-effect) будут выполнены.
которая контролирует когда -  которая контролирует, когда

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Термин *Однофайловый компонент*, или SFC, относится к формату файлов `.vue`, который обычно используется для компонентов Vue.
Термин *Однофайловый компонент*, или SFC,. Я бы чуть по-другому выделил, сохранив смысл:  
Термин *Однофайловый компонент* - SFC - относится...

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +- [Спецификация синтаксиса](/api/sfc-spec.html)
Спецификация синтаксиса - Спецификация синтаксиса SFC

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Браузеры используют дерево узлов для представления текущего состояния страницы. Это дерево и API JavaScript, используемые для взаимодействия с ним, называются *объектной моделью документа(document ob
, или *DOM*. - или *DOM*.

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
>  Rather than creating DOM nodes directly, Vue components generate a description of what DOM nodes they would like. These descriptors are plain JavaScript objects, known as VNodes (virtual DOM nodes).
Английский вариант

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Вместо того чтобы создавать узлы DOM напрямую, компоненты Vue генерируют описание того, какие узлы DOM они хотели бы получить. Эти дескрипторы представляют собой обычные объекты JavaScript, известные
Вместо того чтобы создавать узлы DOM - Вместо того, чтобы создавать узлы DOM

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +Vue использует гибридный подход, который мы называем [Виртуальный DOM на основе данных компилятора](/guide/extras/rendering-mechanism.html#compiler-informed-virtual-dom). Компилятор шаблонов Vue спос
Вместо того чтобы выполнять полное - Вместо того, чтобы выполнять полное

2024-02-12 08:42 UTC, Hekikai commented on src/glossary/index.md
> +- [Руководство - Render-функции & JSX](/guide/extras/render-function.html)
Render-функции & JSX - Render-функции и JSX

2024-02-12 10:47 UTC, Sdju commented
@Hekikai. Большое спасибо за такое объемное ревью! Исправлю/уточню в ближайшее время

2024-02-12 13:43 UTC, Sdju commented on src/glossary/index.md
> +*Асинхронный компонент (async component)* это обертка вокруг другого компонента, которая обеспечивает обёрнутому компоненту ленивую подгруздку. Это типичный способ уменьшить размер сбилженных `.js` ф
Согласен в сочетании "ленивая загрузка". Оно уже устоялось в сообществе. 
Но вот "которые будут подгружены", тут уже "подгрузка" больше подходит по семантике

2024-02-12 13:59 UTC, Sdju commented on src/glossary/index.md
> +Термин *композабл* описывает общий паттерн во Vue. Это не отдельная функция Vue, это просто способ использования подхода [Composition API](#composition-api).
Мне кажется, что уточнение вообще избыточно. Может оставить просто "Это не отдельная возможность во Vue, это просто способ использования Composition API"

2024-02-12 14:34 UTC, Sdju commented on src/glossary/index.md
> +* Композаблы обычно возвращают обычный объект, а не реактивный объект. Этот объект обычно содержит ссылки и функции и, как ожидается, будет деструктуризирован в вызывающем коде.
Процесс: деструктуризация.
Почему эта часть должна стать "деструктурированием"?

2024-02-12 14:38 UTC, Sdju commented on src/glossary/index.md
> +- [Руководство - Render-функции & JSX - Функциональные компоненты](/guide/extras/render-function.html#functional-components)
Тогда на целевой странице нужно это тоже изменить. Сейчас там вариант с &

2024-02-12 14:41 UTC, Sdju commented on src/glossary/index.md
>  ## Options API {#options-api}
А что тут удалять? Тут заголовок

2024-02-12 14:43 UTC, Sdju commented on src/glossary/index.md
> +- [Руководство - Render-функции & JSX](/guide/extras/render-function.html)
Аналогично целевой странице

2024-02-12 14:57 UTC, Sdju commented on src/glossary/index.md
> +Пробрасывание(`provide`) и инъекция(`inject`) - это форма взаимодействия между компонентами.
Переписал весь пункт

2024-02-12 15:03 UTC, Sdju commented on src/glossary/index.md
> +Вместо того чтобы создавать узлы DOM напрямую, компоненты Vue генерируют описание того, какие узлы DOM они хотели бы получить. Эти дескрипторы представляют собой обычные объекты JavaScript, известные
Подсвечивает как ошибку такой вариант
![image](https://github.com/translation-gang/docs-ru/assets/11253427/b2653117-e94b-4d22-b6b1-d8515123fd10)

2024-02-13 04:55 UTC, Ibochkarev requested changes
Необходимо исправить замечания от @Hekikai

2024-02-13 07:04 UTC, Hekikai commented on src/glossary/index.md
> +Термин *композабл* описывает общий паттерн во Vue. Это не отдельная функция Vue, это просто способ использования подхода [Composition API](#composition-api).
Да, так выглядит тоже круто)

2024-02-13 07:05 UTC, Hekikai commented on src/glossary/index.md
> +* Композаблы обычно возвращают обычный объект, а не реактивный объект. Этот объект обычно содержит ссылки и функции и, как ожидается, будет деструктуризирован в вызывающем коде.
Предложил потому, что чаще так говорю. Возможно легче читается даже?  
В целом не крит, но я на стороне "деструктурирован", хоть и процесс называется чуть иначе)

2024-02-13 07:05 UTC, Hekikai commented on src/glossary/index.md
> +- [Руководство - Render-функции & JSX - Функциональные компоненты](/guide/extras/render-function.html#functional-components)
Окей, можно поменять, думаю)

2024-02-13 07:05 UTC, Hekikai commented on src/glossary/index.md
>  ## Options API {#options-api}
Точно, глаз замылился, пока смотрел)

2024-02-13 07:06 UTC, Hekikai commented on src/glossary/index.md
> +- [Руководство - Render-функции & JSX](/guide/extras/render-function.html)
Меняем

2024-02-13 07:07 UTC, Hekikai commented on src/glossary/index.md
> +Вместо того чтобы создавать узлы DOM напрямую, компоненты Vue генерируют описание того, какие узлы DOM они хотели бы получить. Эти дескрипторы представляют собой обычные объекты JavaScript, известные
Да, без запятой выглядит хорошо, оставляем

2024-02-13 07:09 UTC, Hekikai commented on src/glossary/index.md
> +Когда компонент *предоставляет* значение, все потомки этого компонента могут использовать `inject`, чтобы получить это значение. В отличие от входных параметров, компонент предоставляющий значение не
компонент предоставляющий значение не знает, - компонент, предоставляющий значение, не знает,

2024-02-14 04:17 UTC, Ibochkarev approved these changes

2024-02-14 04:17 UTC, merged