feat: start translation rules-strongly-recommended.md
translation-gang/docs-ru pull request #307
Opened 2024-01-23 17:07 UTC by Hekikai

## Description of Problem
Нет перевода для правил приоритета B
## Proposed Solution
Сделал перевод правил приоритета B
## Additional Information
resolved #295

2024-01-23 17:32 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
>  This isn't recommended, as it results in:
Остался оригинальный текст

2024-01-23 17:32 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
>  - Many files with similar names, making rapid file switching in code editors more difficult.
Остался оригинальный текст

2024-01-23 17:33 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
> +- Посколько эти компоненты часто используются, вы, возможно, хотите сделать их глобальными вместо того, чтобы импортировать их везде. Префикс позволяет сделать это в Webpack:
```suggestion
- Посколько эти компоненты часто используются, вы, возможно, захотите сделать их глобальными вместо того, чтобы импортировать их везде. Префикс позволяет сделать это в Webpack:
```

2024-01-23 17:33 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
> +Имена этих файлов часто содержат имя элемента, который используют (например, `BaseButton`, `BaseTable`), если не существует элемента для конкретной цели (например, `BaseIcon`). Если вы будете создава
```suggestion
Имена этих файлов часто содержат имя элемента, который используют (например, `BaseButton`, `BaseTable`), если не существует элемента для конкретной цели (например, `BaseIcon`). Если вы будете создавать похожие компоненты для более специфичного случая, они почти всегда будут использовать базовые компоненты (например `BaseButton` может быть использован в `ButtonSubmit`).
```

2024-01-24 01:29 UTC, Ibochkarev requested changes
поправить замечания

2024-01-24 02:32 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
>  This isn't recommended, as it results in:
```suggestion
```

2024-01-24 02:33 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
>  - Many files with similar names, making rapid file switching in code editors more difficult.
```suggestion
```

2024-01-24 02:33 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
> +- Много файлов с одинаковыми именами, это затрудняет быстро переключаться между файлами в редакторе.
```suggestion
- Много файлов с одинаковыми именами, что затрудняет быстро переключаться между файлами в редакторе.
```

2024-01-24 02:34 UTC, Ibochkarev commented on src/style-guide/rules-strongly-recommended.md
> +- Много вложенных друг в друга папок, это увеличивает время, чтобы найти компонент в левом меню редактора.
```suggestion
- Много вложенных друг в друга папок, что увеличивает время поиска компонента в левом меню редактора. 
```

2024-01-24 02:35 UTC, Ibochkarev approved these changes

2024-01-24 02:35 UTC, merged

2024-01-24 07:41 UTC, Ibochkarev commented
> @Ibochkarev я же не доделал ещё, просто создал PR Мне сделать новый, который переводит до конца?

Aга, если ты еще работаешь — то оставляй PR в режиме Draft

2024-01-24 08:50 UTC, Hekikai commented
Принято, спасибо!