feat: добавлен перевод components/v-model
translation-gang/docs-ru pull request #324
Opened 2024-01-31 22:13 UTC by srsad

## Description of Problem
-

## Proposed Solution
Добавлен перевод components/v-model

## Additional Information
resolved #280

2024-01-31 22:17 UTC, srsad commented
Ребят, ИМХО нужен глоссарий.

2024-02-01 08:14 UTC, vladdof requested changes

2024-02-01 08:14 UTC, vladdof commented on src/guide/components/v-model.md
> +# Компонент v-model {#component-v-model}
Странная фраза Компонент v-model, это же директива вьюшная.

2024-02-01 08:14 UTC, vladdof commented on src/guide/components/v-model.md
> +# Компонент v-model {#component-v-model}
Здесь лучше написать v-model компонента или просто v-model по аналогии с пропсами

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +# Компонент v-model {#component-v-model}
Это не компонент, это v-model внутри компонента. Может спутать людей

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +Значение, возвращаемое функцией `defineModel()`, представляет собой ссылку. К ней можно получить доступ и изменить так же, как и любую другую ссылку, за исключением того, что она действует как двусто
, представляет собой ссылку. - , представляет собой `ref`.  
`ref` мы условились не переводить.  
 между родительским значением и локальным значением -  между родительским и локальным значениями

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +- Значение `.value` синхронизировано с значением, связанным с родительским `v-model`;
с значением - со значением

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +- Когда оно изменяется дочерним элементом, это также приводит к обновлению связанного с родителем значения.
Тяжелое предложение, я бы перефразировал  
Когда оно изменяется дочерним элементом, это приводит к обновлению значения, связанного c родителем.  
Не инвертированный порядок слов легче понимается

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +Это означает, что вы также можете связать эту ссылку к нативному полю ввода с помощью `v-model`, что делает оборачивание элементов ввода простым и обеспечивает аналогичное использование `v-model`:
связать эту ссылку - связать этот `ref`

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +- Свойство с именем `modelValue`, значение которого синхронизировано с значением локальной ссылки;
с значением локальной ссылки - со значением локального `ref`

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +- Событие с именем `update:modelValue`, которое возникает при изменении значения локальной ссылки.
значения локальной ссылки - значения локального `ref`

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +Вот как вы бы реализовали тот же дочерний компонент, который был показан выше до версии 3.4:
компонент, который был показан выше до версии - компонент, который был показан выше, до версии

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +Как видите, это гораздо более многословно. Тем не менее, полезно знать, что происходит под капотом.
это гораздо более многословно. - выглядит как несостыковка в степенях прилагательных.  
Давай попробуем: `это требует чуть больше кода.` И понятно, и смысл не теряется

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +При использовании в компоненте `v-model` вместо этого расширяется до этого:
вместо этого расширяется до этого: - вместо этого расширяется до:  
Два раза повторяется "этого", неприятно читать

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +При использовании в компоненте `v-model` вместо этого расширяется до этого:
При использовании в компоненте - может лучше перевест как "на компоненте"? В целом предлог в английской версии это и означает, а мы можем понять как "внутри компонента", а не "на компоненте"

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +Для того чтобы это действительно работало, компонент `<CustomInput>` должен выполнить две вещи:
Для того чтобы это действительно работало, компонент - Для того, чтобы это действительно работало, компонент

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +2. При срабатывании события `input` элемента `<input>`, генерировать событие `update:modelValue` с новым значением
Во втором предложении не нужна запятая совсем

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +В дочернем компоненте мы можем поддерживать соответствующий аргумент, передав строку в `defineModel()` в качестве его первого аргумента
Пропущено двоеточие

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +Используя возможность указывать конкретное свойство и событие, как мы узнали ранее с [аргументами `v-model`](#v-model-arguments), теперь мы можем создать несколько `v-model` привязок на одном экземпл
несколько `v-model` привязок на одном - несколько `v-model` на одном  
Думаю, слово "привязок" тут лишнее, смысл не теряется, все понятно и так

2024-02-01 08:24 UTC, Hekikai commented on src/guide/components/v-model.md
> +Чтобы условно настроить чтение/запись значения на основе модификаторов, мы можем передать опции `get` и `set` в `defineModel()`. Эти две опции получают значение при получении / установке ссылки на мо
чтение/запись значения -  чтение / запись значения
при получении / установке ссылки на модель - при получении / установки `ref` на модель

2024-02-01 10:40 UTC, srsad commented on src/guide/components/v-model.md
> +Поскольку `defineModel` объявляет входные параметры, вы можете также объявить входные параметры основного свойства, передав его в `defineModel`:
> входные параметры(props)

Согласен, но в проекте уже используется без дополнительного пояснения.

2024-02-01 10:44 UTC, srsad commented on src/guide/components/v-model.md
> +Значение, возвращаемое функцией `defineModel()`, представляет собой ссылку. К ней можно получить доступ и изменить так же, как и любую другую ссылку, за исключением того, что она действует как двусто
Отлично, поменяю везде где перевел.
Можно линк, где условились?

2024-02-01 20:13 UTC, Hekikai commented on src/guide/components/v-model.md
> +Значение, возвращаемое функцией `defineModel()`, представляет собой ссылку. К ней можно получить доступ и изменить так же, как и любую другую ссылку, за исключением того, что она действует как двусто
Еще бы найти этот PR...  
Думаю, как Ваня доберется до этого PR-а - ответит...

2024-02-03 03:14 UTC, Ibochkarev requested changes
Ждем исправления замечаний

2024-02-03 22:09 UTC, srsad commented
@Ibochkarev может сделать общий чатик в телеге, для более продуктивной коммуникации? В рамках чата можно будет и договариваться об использовании тех или иных терминов + параллельно редактировать глоссарий (который потом появиться).

2024-02-04 11:03 UTC, Ibochkarev commented
> @Ibochkarev может сделать общий чатик в телеге, для более продуктивной коммуникации? В рамках чата можно будет и договариваться об использовании тех или иных терминов + параллельно редактировать глоссарий (который потом появиться).

@srsad @Hekikai @vladdof велком https://t.me/+FfEj6pNvVWgwZDgy

2024-02-05 05:47 UTC, Ibochkarev approved these changes

2024-02-05 05:47 UTC, merged