Перевод страницы Sponsors
translation-gang/docs-ru pull request #340
Opened 2024-02-12 03:20 UTC by Sdju

Реализация #321

2024-02-12 04:04 UTC, Ibochkarev requested changes

2024-02-12 04:04 UTC, Ibochkarev commented on src/sponsor/index.md
> +## Как Спонсировать? {#how-to-sponsor}
Зачем спонсировать с большой?

2024-02-12 04:04 UTC, Ibochkarev commented on src/sponsor/index.md
> +## Спонсирование Vue как Частное Лицо {#sponsoring-vue-as-an-individual}
Зачем все с заглавной?

2024-02-12 04:04 UTC, Ibochkarev commented on src/sponsor/index.md
> +## Преимущества за Уровень {#tier-benefits}
Зачем все с заглавной?

2024-02-12 07:29 UTC, Sdju commented on src/sponsor/index.md
> +## Как Спонсировать? {#how-to-sponsor}
Так вроде в целом на сайте все кроме предлогов в заголовках с большой

2024-02-12 07:31 UTC, Sdju commented on src/sponsor/index.md
> +## Как Спонсировать? {#how-to-sponsor}
Да еще раз посмотрел другие страницы. Все-таки решили писать все кроме первой с маленькой

2024-02-12 07:39 UTC, Sdju commented on src/sponsor/index.md
> +## Как Спонсировать? {#how-to-sponsor}
Исправлено

2024-02-13 04:53 UTC, Ibochkarev approved these changes

2024-02-13 04:53 UTC, merged