Translation of the Built-in Components topic
translation-gang/docs-ru pull request #52
Opened 2022-11-06 14:10 UTC by d-darwin

## Description of Problem

Раздел документации переведён не полностью

## Proposed Solution

Предложен вариант перевода

2022-11-07 06:32 UTC, d-darwin commented
Имеет смысл подправить в соответствии с глоссарием
https://github.com/translation-gang/docs-ru/discussions/55

2022-11-07 07:48 UTC, Alex-Sokolov requested changes

2022-11-07 07:48 UTC, Alex-Sokolov commented on src/api/built-in-components.md
> +При использовании в [функции рендеринга](/guide/extras/render-function.html), они должны быть импортированы в явном виде. Например:
Обычно в документации render-функциями и называли везде

2022-11-07 07:48 UTC, Alex-Sokolov commented on src/api/built-in-components.md
> +     * По умолчанию Vue ждёт первого события `transitionend`
Если тут висящий пробел в конце, а не просто так дифф показывает гитхаб, то его стоит убрать

2022-11-07 07:48 UTC, Alex-Sokolov commented on src/api/built-in-components.md
> +     * Управляет последовательностью переходов исчезновения/появления.
И тут похоже тоже висящий

2022-11-07 07:48 UTC, Alex-Sokolov commented on src/api/built-in-components.md
> +     * Если не определен, то рендериться как fragment.
Без мягкого знака

2022-11-07 07:48 UTC, Alex-Sokolov commented on src/api/built-in-components.md
> +  `<TransitionGroup>` поддерживает анимации перемещения с помощью CSS трансформаций. Если положение потомка на экране измениться после обновления, ему будет добавлен CSS-класс (автоматически сгенерир
`измениться` тоже без мягкого знака

2022-11-07 07:48 UTC, Alex-Sokolov commented on src/api/built-in-components.md
>    <!-- comma-delimited string -->
В примерах комментарии тоже можно посмотреть ещё раз что переведены

2022-11-07 07:48 UTC, Alex-Sokolov commented on src/api/built-in-components.md
> +     * Может быть селектором или настоящим элементом.
"Настоящий элемент" не очень понятно может звучать. Может "непосредственно элементом"?

2022-11-07 07:48 UTC, Alex-Sokolov commented
Спасибо за PR :) добавил несколько мелких комментариев

2022-11-07 18:08 UTC, d-darwin commented
:fixed:

2022-11-07 18:09 UTC, d-darwin commented
@Alex-Sokolov 
Пофиксил.

2022-11-08 11:11 UTC, merged

2022-11-08 11:11 UTC, Alex-Sokolov commented
Спасибо! :)