Issue 62
translation-gang/docs-ru pull request #63
Opened 2022-11-13 14:19 UTC by d-darwin

Closes https://github.com/translation-gang/docs-ru/issues/62

2022-11-13 18:42 UTC, Alex-Sokolov requested changes

2022-11-13 18:42 UTC, Alex-Sokolov commented on src/api/built-in-special-attributes.md
> +  Без ключей Vue использует алгоритм, который минимизирует перемещение элемент и пытается изменять/переиспользовать элементы одного типа как можно больше. При использовании ключей Vue переупорядочива
Перемещение элементов наверное?
Про ключи как-то повторяется, в прошлой доке тоже с повторениями?

2022-11-13 18:42 UTC, Alex-Sokolov commented on src/api/built-in-special-attributes.md
> +  <!-- Храниться в this.$refs.p -->
Без мягкого знака думаю / или "будет храниться"

2022-11-13 18:42 UTC, Alex-Sokolov commented on src/api/built-in-special-attributes.md
> +  Однако, есть случай использования, когда может понадобиться, чтобы Vue заменил нативный элемент на компонент Vue, как это разъясняется в [DOM Template Parsing Caveats](/guide/essentials/component-b
Заголовок той страницы скорее всего будет называться как и в прошлой доке "Особенности парсинга DOM-шаблона"

2022-11-13 18:42 UTC, Alex-Sokolov commented
@d-darwin спасибо за PR! Пару комментариев добавил :)

2022-11-14 06:11 UTC, d-darwin commented on src/api/built-in-special-attributes.md
> +  Без ключей Vue использует алгоритм, который минимизирует перемещение элемент и пытается изменять/переиспользовать элементы одного типа как можно больше. При использовании ключей Vue переупорядочива
Про повторение не совсем понял. Сначала, что будет без ключей, потом - что будет с ключами.
Вот прошлая дока: https://v3.ru.vuejs.org/ru/api/special-attributes.html#key

2022-11-15 21:14 UTC, merged

2022-11-15 21:14 UTC, Alex-Sokolov commented
Спасибо